CREATE TABLE Measure (
  Id int(11) NOT NULL AUTO_INCREMENT,
  Time datetime NOT NULL,
  Temperature double DEFAULT NULL,
  PRIMARY KEY (Id)
) ENGINE=InnoDB AUTO_INCREMENT=8597 DEFAULT CHARSET=utf8mb4